name: Shelve
options:
  bundleIdPrefix: com.muchbetteradventures.shelve
  deploymentTarget:
    macOS: "14.0"
settings:
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_STYLE: Manual
  CODE_SIGN_IDENTITY: "Developer ID Application"
  ENABLE_HARDENED_RUNTIME: YES
  GENERATE_INFOPLIST_FILE: YES

targets:
  Shelve:
    type: application
    platform: macOS
    sources:
      - Shelve
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.muchbetteradventures.shelve.app
      PROVISIONING_PROFILE_SPECIFIER: "Shelve App Provisioning"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_VALUES:
        CFBundleDisplayName: Shelve
        CFBundleName: Shelve
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    dependencies:
      - target: "Shelve Extension"

  Shelve Extension:
    type: app-extension
    platform: macOS
    sources:
      - "Shelve Extension"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.muchbetteradventures.shelve.app.extension
      PROVISIONING_PROFILE_SPECIFIER: "Shelve App Extension Provisioning"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: "Shelve Extension/Info.plist"
      INFOPLIST_VALUES:
        CFBundleDisplayName: "Shelve Extension"
        CFBundleName: "Shelve Extension"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
      CODE_SIGN_ENTITLEMENTS: "Shelve Extension/Shelve_Extension.entitlements"
